version: '3'
services:
  ruby:
    restart: unless-stopped
    image: 'motortruck1221/ruby:latest'
    ports:
      #DO NOT CHANGE 9293!
      - your port here:9293
    volumes:
      - ./config.yml:/usr/src/app/config/settings.yml

 #
  # Uncomment the following lines if you want to use a database (mutliuser mode)
  #db:
  #  image: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_PASSWORD: ruby
  #    POSTGRES_USER: ruby
  #    POSTGRES_DB: ruby
  
  # Uncomment the following lines if you want to use adminer (database management)
  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8099:8080
